{% set name = "pugixml" %}
{% set version = "1.11.3" %}
{% set sha256 = "3a215dd7bd9cecaf5edf690ac9045e8f83e4a865004f01b8f0a351a037a6ef06" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/zeux/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('pugixml', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - test -f "${PREFIX}/lib/libpugixml.a"  # [unix]
    - test -f "${PREFIX}/include/pugixml.hpp"  # [unix]
    - if not exist %LIBRARY_LIB%\\pugixml.lib exit 1  # [win]
    - if not exist %LIBRARY_INC%\\pugiconfig.hpp exit 1  # [win]

about:
  home: http://pugixml.org/
  license: MIT
  license_family: MIT
  license_file: README.md
  summary: Light-weight, simple and fast XML parser for C++ with XPath support
  description: |
    pugixml is a C++ XML processing library, which consists of a DOM-like interface
    with rich traversal/modification capabilities, an extremely fast XML parser which
    constructs the DOM tree from an XML file/buffer, and an XPath 1.0 implementation
    for complex data-driven tree queries. Full Unicode support is also available, with
    Unicode interface variants and conversions between different Unicode encodings
    (which happen automatically during parsing/saving)
  doc_url: http://pugixml.org/
  dev_url: https://github.com/zeux/pugixml

extra:
  recipe-maintainers:
    - scopatz
    - SylvainCorlay
